### ISSUE TITLE
getting error with latest version of library 4.0.20

### ISSUE THREAD

**Issue by myeduapp** [chat-sdk/chat-sdk-android#276] opened 2018-04-29 11:18 UTC
Getting error after updating to to the latest version 
![image](https://user-images.githubusercontent.com/32955380/39405996-43ee54e4-4bcd-11e8-8206-fbd6992d0f64.png)

**Comment by ggcarmi** [comment] 2018-05-23 14:26
i got the same error
do you found a solution?

**Comment by myeduapp** [comment] 2018-05-24 06:51
@ggcarmi No I am still getting same error.

**Comment by bensmiley** [comment] 2018-05-24 08:49
Could you try updating to 4.0.26?

**Comment by thecmart** [comment] 2019-06-28 14:31
@myeduapp We could not reproduce this problem in the newest version of Chat SDK, so we will close this issue. If the issue persists, please re-open it.

**Closed by thecmart** 2019-06-28 14:31 UTC
Labels: Cannot reproduce in version 4.4.9
