### ISSUE TITLE
Bug with sending image message

### ISSUE THREAD

**Issue by Jinqianv** [chat-sdk/chat-sdk-android#198] opened 2017-12-11 12:44 UTC
- Is the bug present in the demo Chat SDK project? (yes/no)
yes
- Steps taken to reproduce bug:
once sending an image message and go back to the thread list.
and again enter any chat activity, then I can not send image message.
- Expected result:
should be moved to the crop image activity.
- Actual result:
gallery is just closed 
- Comments:
onActivityResult in ChatActivity was not called by clicking gallery image item.

**Comment by bensmiley** [comment] 2017-12-14 17:17
Seems to be a duplicate of #195.

**Closed by bensmiley** 2017-12-14 17:17 UTC
Labels: bug
