### ISSUE TITLE
Take Photo sends rotated image.

### ISSUE THREAD

**Issue by paakjis** [chat-sdk/chat-sdk-android#267] opened 2018-04-17 13:33 UTC
Take Photo sends rotated and low quality photo.
The code is written to send a thumbnail image to other person.
In MediaSelector , resultHandler.result(path), where path is where MediaStore.ACTION_IMAGE_CAPTURE saved the image.

I fixed it on my project, just letting you know there is an issue.
This helped me https://stackoverflow.com/questions/10377783/low-picture-image-quality-when-capture-from-camera/10382217

**Comment by dogacsenol** [comment] 2018-10-28 21:15
@bensmiley I don't know about rotated, but image quality is really low on Android when capturing and then sending a photo. iOS is fine. Can you have a quick look? Thanks.

**Comment by bensmiley** [comment] 2018-10-29 14:13
I tested this and it seems to be solved as of `4.3.3`. If you are getting this issue with the latest version of the project, could you post the before and after photos? Since I can't reproduce this, I'm closing the issue but if you are getting it with the latest version, you can reopen the issue.

**Closed by bensmiley** 2018-10-29 14:13 UTC

**Comment by zaramma** [comment] 2018-12-04 23:39
@bensmiley ,I am using 4.4.3, rotation issue still exists in Android. Happens in Samsung and blackberry devices, photo rotates to the left. Uploading from gallery works fine.
