### ISSUE TITLE
When app is swiped out or killed then come back again didn't receive any push notification.

### ISSUE THREAD

**Issue by ominfowave** [chat-sdk/chat-sdk-android#388] opened 2018-10-05 10:56 UTC
_Originally posted by @ominfowave in https://github.com/chat-sdk/chat-sdk-android/issues/362#issuecomment-427274881_

**Comment by thecmart** [comment] 2019-06-28 15:05
@ominfowave We could not reproduce this problem in the newest version of Chat SDK, so we will close this issue. If the issue persists, please re-open it.

**Closed by thecmart** 2019-06-28 15:05 UTC
Labels: Cannot reproduce in version 4.4.9
