### ISSUE TITLE
Push notifications after logout (Firebase)

### ISSUE THREAD

**Issue by Aeryltic** [chat-sdk/chat-sdk-android#280] opened 2018-05-10 08:58 UTC
I'm receiving push notifications no matter if I logged out the user or even logged in as another one - then I receive notifications for both users. I don't see anyone else with the same issue here so I guess it's my fault. I have followed [https://github.com/chat-sdk/docs#custom-authentication](url) because my app has its own server and [https://github.com/chat-sdk/chat-sdk-android#push-notifications](url). I use modified version of ChatActivity that extends your BaseActivity - not ChatActivity itself, but it works, even when I tap on notification. When user logs out from the app NM.auth().logout().subscribe(...) is called. All my activities extend your BaseActivity.

**Comment by Criticblack** [comment] 2018-10-01 11:20
https://stackoverflow.com/questions/43193215/firebase-cloud-messaging-handling-logout

**Comment by thecmart** [comment] 2019-06-28 14:43
@Aeryltic We could not reproduce this problem in the newest version of Chat SDK, so we will close this issue. If the issue persists, please re-open it.

**Closed by thecmart** 2019-06-28 14:43 UTC
Labels: Cannot reproduce in version 4.4.9
