### ISSUE TITLE
On Reinstalling the application with same credentials... unread count is wrong

### ISSUE THREAD

**Issue by rahulsharmagbpec** [chat-sdk/chat-sdk-android#375] opened 2018-09-21 10:02 UTC
I reinstalled the application and logged in with same credential which i was using before, now the total number of messages is thread is showing as unread count.

**Comment by thecmart** [comment] 2019-06-28 15:01
@rahulsharmagbpec We could not reproduce this problem in the newest version of Chat SDK, so we will close this issue. If the issue persists, please re-open it.

**Closed by thecmart** 2019-06-28 15:01 UTC
Labels: Cannot reproduce in version 4.4.9

**Comment by anonym24** [comment] 2020-11-19 09:56
this issue is still available in every 5 versions, including the latest 5.0.16

**Comment by anonym24** [comment] 2020-11-19 09:57
@thecmart how did you test it? please check 5.0.16. Install the app, create at least 5 threads with different users, those users has to send some message to you, then reinstall the app (fully delete and install again) or clear data, login with the same user and you will see unread counter on all or some threads

**Comment by slpatidar** [comment] 2021-01-27 09:02
> @thecmart how did you test it? please check 5.0.16. Install the app, create at least 5 threads with different users, those users has to send some message to you, then reinstall the app (fully delete and install again) or clear data, login with the same user and you will see unread counter on all or some threads

Yes, I m facing exactly the same issue in the latest version as well. and as per my understanding, there is no syncing with the firebase realtime database for "read" status mark in free SDK, this is just maintaining the read unread mark in the local database so when we uninstall the app database will be cleared and then install the app all thread messages becomes show as a new unread message.
