### ISSUE TITLE
i have a project needs chat SDK

### ISSUE THREAD

**Issue by NguyenSon3122** [chat-sdk/chat-sdk-android#531] opened 2019-05-14 07:24 UTC
i have a project needs chat SDK, we bought 2 lisences for 2 modules: Read Receipts for Android and  Sticker Messages for Android, but i cant add that 3 modules to my project, anyone had solved it before please help! ......................

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: co.chatsdk.android.app, PID: 24315
    java.lang.IllegalAccessError: Method 'void co.chatsdk.core.base.AbstractAuthenticationHandler.setAuthStateToIdle()' is inaccessible to class 'co.chatsdk.firebase.-$$Lambda$uGm_CejYsNazMka97kJYXdvzfK0' (declaration of 'co.chatsdk.firebase.-$$Lambda$uGm_CejYsNazMka97kJYXdvzfK0' appears in /data/app/co.chatsdk.android.app-D7QLHe2OxgT2hAigK2X75Q==/split_lib_dependencies_apk.apk)
        at co.chatsdk.firebase.-$$Lambda$uGm_CejYsNazMka97kJYXdvzfK0.run(Unknown Source:2)
        at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(CompletablePeek.java:108)
        at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onComplete(SingleFlatMapCompletable.java:102)
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onComplete(CompletableSubscribeOn.java:79)
        at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onComplete(CompletableCreate.java:64)
        at co.chatsdk.firebase.-$$Lambda$1glDl6ZgqumHpaWnZaQBW1D-mho.run(Unknown Source:2)
        at io.reactivex.internal.observers.CallbackCompletableObserver.onComplete(CallbackCompletableObserver.java:53)
        at io.reactivex.internal.operators.completable.CompletableAndThenCompletable$NextObserver.onComplete(CompletableAndThenCompletable.java:99)
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onComplete(CompletableSubscribeOn.java:79)
        at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onComplete(CompletableCreate.java:64)
        at co.chatsdk.firebase.wrappers.UserWrapper.lambda$updateIndex$10(UserWrapper.java:352)
        at co.chatsdk.firebase.wrappers.-$$Lambda$UserWrapper$Mpfgv8sKoBxRPSeDtNRBVdrYztA.onComplete(Unknown Source:2)
        at com.google.firebase.database.core.Repo$6.run(com.google.firebase:firebase-database@@16.1.0:402)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
E/EGL_emulation: tid 24364: swapBuffers(550): error 0x300d (EGL_BAD_SURFACE) 
```

**Comment by bensmiley** [comment] 2019-05-14 09:49
Hi @NguyenSon3122 can you tell me which version of the modules you are using and which version of the core library? Also, when does this error occur? Can you provide the steps to reproduce it?

**Comment by NguyenSon3122** [comment] 2019-05-14 09:57
version of the modules: 4.6.9 
version of the core library: 4.7.5

**Comment by bensmiley** [comment] 2019-05-14 09:59
Could you try downgrading to version 4.7.1 of the core library? We will also be releasing a new update to the modules today so if you can wait a few hours, it would be worth updating to that.

**Comment by NguyenSon3122** [comment] 2019-05-14 10:00
I wait for the update, I don't need to downgrade the version ?

**Comment by NguyenSon3122** [comment] 2019-05-14 10:19
I tried to downgrade to 4.7.1 but it didn't work.....

**Comment by bensmiley** [comment] 2019-05-14 10:20
Ok, if you wait a few hours, you can update to the latest version. If you have problems with that, I can support you directly.

**Comment by NguyenSon3122** [comment] 2019-05-20 03:41
My 2 modules that are sticker and Read Receipts have updated 4.8.2 I cannot integrate. please help me

**Comment by bensmiley** [comment] 2019-05-20 13:22
Hi @NguyenSon3122 can you tell me what problem you're having? Did you manage to download the modules from the website? Are you seeing any compile time or run time errors?

**Comment by NguyenSon3122** [comment] 2019-05-21 01:28
thư viện của tôi : 4.7.5  module sticker and read-receipts  4.8.2 
![error](https://user-images.githubusercontent.com/46442621/58061826-0fb5c580-7ba2-11e9-83f2-761561c1aa70.png)

**Comment by NguyenSon3122** [comment] 2019-05-21 01:35
I tried adding 2 modules to the original version 4.8.2  that encountered this error ..... you can support me via teamview
![error](https://user-images.githubusercontent.com/46442621/58062133-696abf80-7ba3-11e9-8d1d-2eba2061d5fd.png)

**Comment by thecmart** [comment] 2019-07-01 14:59
@NguyenSon3122 Can you please let me know if these problems still exist in the Chat SDK 4.8.2a3 version?

**Comment by ajuarmia** [comment] 2019-07-03 09:30
I am also facing the same issue.Give solution

**Comment by bensmiley** [comment] 2019-07-03 15:59
Closing because it's a duplicate: https://github.com/chat-sdk/chat-sdk-android/issues/548.

**Closed by bensmiley** 2019-07-03 15:59 UTC
Labels: investigating
