### ISSUE TITLE
Crashes when opening images from the thread

### ISSUE THREAD

**Issue by snipe717** [chat-sdk/chat-sdk-android#272] opened 2018-04-26 13:41 UTC
Still getting app crashes when previewing images at full screen. I was unable to replicate this myself, but two of my users found this problem.

**Comment by thecmart** [comment] 2019-06-28 14:13
@snipe717 We could not reproduce this problem in the newest version of Chat SDK, so we will close this issue. If the issue persists, please re-open it.

**Closed by thecmart** 2019-06-28 14:13 UTC
Labels: Cannot reproduce in version 4.4.9
