### ISSUE TITLE
Type sdk.chat.core.BuildConfig is defined multiple times

### ISSUE THREAD

**Issue by RahatSaqib** [chat-sdk/chat-sdk-android#637] opened 2020-07-10 15:57 UTC
When I am going to release the full app it says this error:
Type sdk.chat.core.BuildConfig is defined multiple times: F:\works\New Folder\Ramfolinee\chat-sdk-core\build\.transforms\01ae4b258926b7a18889d4cd8c45b46a\classes\classes.dex, F:\works\New Folder\Ramfolinee\app\build\intermediates\external_libs_dex\developmentRelease\out\classes5.dex

![gradle](https://user-images.githubusercontent.com/37343956/87173907-3bd95c00-c2f8-11ea-9e76-fb328c0df31a.PNG)
I want to release app with your chatsdk features.

**Comment by bensmiley** [comment] 2020-07-10 16:05
@RahatSaqib which Chat SDK version are you using?

**Comment by RahatSaqib** [comment] 2020-07-10 16:08
version 5.0.0rc21

**Comment by bensmiley** [comment] 2020-07-10 16:09
Can you update to `5.0.4`?

**Comment by RahatSaqib** [comment] 2020-07-10 16:10
yes.but It will take time which cost do it from start. Is this a version issue? I don't think so

**Comment by RahatSaqib** [comment] 2020-07-10 16:12
but currently in github it shows 5.0.2 no 5.0.4

**Comment by bensmiley** [comment] 2020-07-10 16:13
@RahatSaqib it's possible that there was a problem was caused by the android manifest in two of the modules sharing a package name. This is resolved in the newest version. You can see the latest version here:

https://hackmd.io/@dyR2Vn0UTFaO8tZjyiJyHw/B1S2tXdqL#App-level-buildgradle

**Comment by RahatSaqib** [comment] 2020-07-11 06:08
But I can not get the 5.0,4 . Where should i download?

**Comment by bensmiley** [comment] 2020-07-11 10:14
You can get it using Gradle. https://hackmd.io/@dyR2Vn0UTFaO8tZjyiJyHw/B1S2tXdqL#Add-Chat-SDK-to-your-project

**Closed** 2020-07-13 11:54 UTC
