### ISSUE TITLE
Unable to build the app with latest version of library 4.4.8

### ISSUE THREAD

**Issue by myeduapp** [chat-sdk/chat-sdk-android#456] opened 2018-12-25 15:40 UTC
1. **Is the bug present in the demo Chat SDK project?**
No
2. **What modifications have you made to the Chat SDK?**
No
3. **Android Version:**

4. **Steps taken to reproduce the problem:**

5. **Expected result:**
Should be able to build the app.Is it because of AndroidX
6. **Actual result:**

7. **Comments:**
Also I am using firebase as a backend for other functionality.
I am using authenticateWithCatchedToken method to setup chatsdk when user signs in. and using below code to logout.

 [FirebaseAuth.getInstance().signOut();
                ChatSDK.auth().logout().subscribe(() -> {
                    // Success
                }, throwable -> {
                    // Error
                });](url)

After this I continuously get error io.reactivex.exceptions.OnErrorNotImplementedException.
I am not using ReactiveX in my project.
Please help.

**Comment by tobimichigan** [comment] 2018-12-26 21:32
I'm not sure if chat-sdk supports reactive x yet. Why not go with the normal Android repo?

**Comment by myeduapp** [comment] 2018-12-27 12:16
@tobimichigan Yes as per the documentation it supports.

**Comment by bensmiley** [comment] 2019-01-07 10:46
The main app does support Android X. I'm closing this issue because we can't reproduce it but if you still see it could you post an error log.

**Closed by bensmiley** 2019-01-07 10:46 UTC
Labels: Cannot reproduce in version 4.4.9

**Comment by adapana** [comment] 2019-03-30 10:16
This issue is happening lastest code. When  I log out using `ChatSDK.auth().logout().subscribe();` code.
When I log in again then the app crashes every time.
