### ISSUE TITLE
got IllegalArgumentException when phone was on idle condition, logs given below

### ISSUE THREAD

**Issue by rahulsharmagbpec** [chat-sdk/chat-sdk-android#384] opened 2018-10-05 07:34 UTC
Crash is in this line

```
Collections.sort(threads, new ThreadsSorter());

E/UncaughtException: java.lang.IllegalArgumentException: Comparison method violates its general contract!
                                                                            at java.util.TimSort.mergeHi(TimSort.java:899)
                                                                            at java.util.TimSort.mergeAt(TimSort.java:516)
                                                                            at java.util.TimSort.mergeCollapse(TimSort.java:441)
                                                                            at java.util.TimSort.sort(TimSort.java:245)
                                                                            at java.util.Arrays.sort(Arrays.java:1498)
                                                                            at java.util.Collections.sort(Collections.java:205)
                                                                            at co.chatsdk.core.base.AbstractThreadHandler.getThreads(AbstractThreadHandler.java:193)
                                                                            at co.chatsdk.core.base.AbstractThreadHandler.getThreads(AbstractThreadHandler.java:154)
                                                                            at co.chatsdk.core.base.AbstractThreadHandler.getThreads(AbstractThreadHandler.java:149
```

**Comment by bensmiley** [comment] 2019-01-07 10:53
I reviewed the code and couldn't see anything that was obviously wrong. I think this could be caused by data corruption because I've never seen it before. So I'm closing the issue for now.

**Closed by bensmiley** 2019-01-07 10:53 UTC
Labels: Cannot reproduce in version 4.4.9
