### ISSUE TITLE
Cannot delete old threads, showing as THREAD

### ISSUE THREAD

**Issue by snipe717** [chat-sdk/chat-sdk-android#271] opened 2018-04-26 13:39 UTC
Issue seems to stem from fresh installing the app and logging in with previous credentials, old threads become problematic and cannot be deleted. This also leads to oddities when trying to pick up old conversations

**Comment by thecmart** [comment] 2019-06-28 14:08
@snipe717 We could not reproduce this problem in the newest version of Chat SDK, so we will close this issue. If the issue persists, please re-open it.

**Closed by thecmart** 2019-06-28 14:08 UTC
Labels: Cannot reproduce in version 4.4.9
