### ISSUE TITLE
SplashScreenActivity logoDrawableResourceID on a null object reference

### ISSUE THREAD

**Issue by johnx32** [chat-sdk/chat-sdk-android#542] opened 2019-06-22 00:28 UTC
1. **Is the bug present in the demo Chat SDK project?**
   no
2. **What modifications have you made to the Chat SDK?**
     nothing
3. **Android Version:**
     minSdkVersion 17       targetSdkVersion 28
4. **Steps taken to reproduce the problem:**
   launch   SplashScreenActivity
5. **Expected result:**
    launch   SplashScreenActivity
6. **Actual result:**
   the error mesage
<pre>
06-21 20:06:03.822 22115-22115/? E/Zygote: MountEmulatedStorage()
06-21 20:06:03.822 22115-22115/? E/Zygote: v2
06-21 20:06:03.842 22115-22115/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
06-21 20:06:03.842 22115-22115/? E/art: setrlimit(RLIMIT_CORE) failed for pid 22115: Operation not permitted
06-21 20:06:06.264 22115-22115/redestic.org.tag7 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: redestic.org.tag7, PID: 22115
    java.lang.RuntimeException: Unable to start activity ComponentInfo{redestic.org.tag7/co.chatsdk.ui.login.SplashScreenActivity}: java.lang.NullPointerException: Attempt to read from field 'int co.chatsdk.core.session.Configuration.logoDrawableResourceID' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3150)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3260)
        at android.app.ActivityThread.access$1000(ActivityThread.java:218)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1734)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6934)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'int co.chatsdk.core.session.Configuration.logoDrawableResourceID' on a null object reference
        at co.chatsdk.ui.main.BaseActivity.getTaskDescriptionBitmap(BaseActivity.java:86)
        at co.chatsdk.ui.main.BaseActivity.onCreate(BaseActivity.java:66)
        at co.chatsdk.ui.login.SplashScreenActivity.onCreate(SplashScreenActivity.java:25)
        at android.app.Activity.performCreate(Activity.java:6609)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3103)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3260) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:218) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1734) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:145) 
        at android.app.ActivityThread.main(ActivityThread.java:6934) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
</pre>

7. **Comments:**
   I import all the libreri libraries following the steps of the page.
   i have ic_launcher_big.png in the proyect

**Comment by thecmart** [comment] 2019-06-28 12:51
Hello John, I suspect that your root path might have one or more dashes "-" in it. This is a frequent issue that causes the try{ block in the AppObj class to fail. Please let me know if your root path in the AppObj class "config.firebaseRootPath(" ");" has no dashes in it, and if it does, remove them and try it again.

**Comment by thecmart** [comment] 2019-06-28 13:12
> 
> 
>     1. **Is the bug present in the demo Chat SDK project?**
>        no
> 
>     2. **What modifications have you made to the Chat SDK?**
>        nothing
> 
>     3. **Android Version:**
>        minSdkVersion 17       targetSdkVersion 28
> 
>     4. **Steps taken to reproduce the problem:**
>        launch   SplashScreenActivity
> 
>     5. **Expected result:**
>        launch   SplashScreenActivity
> 
>     6. **Actual result:**
>        the error mesage
> 
> 
> 06-21 20:06:03.822 22115-22115/? E/Zygote: MountEmulatedStorage()
> 06-21 20:06:03.822 22115-22115/? E/Zygote: v2
> 06-21 20:06:03.842 22115-22115/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
> 06-21 20:06:03.842 22115-22115/? E/art: setrlimit(RLIMIT_CORE) failed for pid 22115: Operation not permitted
> 06-21 20:06:06.264 22115-22115/redestic.org.tag7 E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: redestic.org.tag7, PID: 22115
>     java.lang.RuntimeException: Unable to start activity ComponentInfo{redestic.org.tag7/co.chatsdk.ui.login.SplashScreenActivity}: java.lang.NullPointerException: Attempt to read from field 'int co.chatsdk.core.session.Configuration.logoDrawableResourceID' on a null object reference
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3150)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3260)
>         at android.app.ActivityThread.access$1000(ActivityThread.java:218)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1734)
>         at android.os.Handler.dispatchMessage(Handler.java:102)
>         at android.os.Looper.loop(Looper.java:145)
>         at android.app.ActivityThread.main(ActivityThread.java:6934)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at java.lang.reflect.Method.invoke(Method.java:372)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
>      Caused by: java.lang.NullPointerException: Attempt to read from field 'int co.chatsdk.core.session.Configuration.logoDrawableResourceID' on a null object reference
>         at co.chatsdk.ui.main.BaseActivity.getTaskDescriptionBitmap(BaseActivity.java:86)
>         at co.chatsdk.ui.main.BaseActivity.onCreate(BaseActivity.java:66)
>         at co.chatsdk.ui.login.SplashScreenActivity.onCreate(SplashScreenActivity.java:25)
>         at android.app.Activity.performCreate(Activity.java:6609)
>         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3103)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3260) 
>         at android.app.ActivityThread.access$1000(ActivityThread.java:218) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1734) 
>         at android.os.Handler.dispatchMessage(Handler.java:102) 
>         at android.os.Looper.loop(Looper.java:145) 
>         at android.app.ActivityThread.main(ActivityThread.java:6934) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at java.lang.reflect.Method.invoke(Method.java:372) 
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
> 
>     1. **Comments:**
>        I import all the libreri libraries following the steps of the page.
>        i have ic_launcher_big.png in the proyect

Hello John, I suspect that your root path might have one or more dashes "-" in it. This is a frequent issue that causes the try{ block in the AppObj class to fail. Please let me know if your root path in the AppObj class "config.firebaseRootPath(" ");" has no dashes in it, and if it does, remove them and try it again.

**Comment by sapoluri** [comment] 2019-10-15 16:28
Saw something similar:
2019-10-15 09:19:54.186 5825-5825/com.legato.music E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.legato.music, PID: 5825
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.legato.music/co.chatsdk.ui.login.SplashScreenActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View androidx.constraintlayout.widget.ConstraintLayout.getViewById(int)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View androidx.constraintlayout.widget.ConstraintLayout.getViewById(int)' on a null object reference
        at co.chatsdk.ui.login.SplashScreenActivity.onCreate(SplashScreenActivity.java:31)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-10-15 09:19:54.187 1741-1752/? E/storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
2019-10-15 09:19:58.189 5825-5825/com.legato.music E/CrashlyticsCore: Failed to execute task.
    java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at com.crashlytics.android.core.CrashlyticsBackgroundWorker.submitAndWait(CrashlyticsBackgroundWorker.java:41)
        at com.crashlytics.android.core.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:321)
        at com.crashlytics.android.core.CrashlyticsController$6.onUncaughtException(CrashlyticsController.java:301)
        at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:42)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
        at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)

I checked in the try catch block by putting a breakpoint. There was no exception thrown there.
This is version 4.8.4

**Closed** 2020-06-11 11:30 UTC
Labels: investigating
