### ISSUE TITLE
Logcat error Didn't find class "net.sqlcipher.database.SQLiteOpenHelper"

### ISSUE THREAD

**Issue by agustinsivoplas** [chat-sdk/chat-sdk-android#281] opened 2018-05-11 16:04 UTC
I trying to use ChatSDK, this error is continuosly logged. Any idea how to fix it?

```
Caused by: java.lang.ClassNotFoundException: Didn't find class "net.sqlcipher.database.SQLiteOpenHelper" on path: DexPathList[[zip file "/data/app
.....
Rejecting re-init on previously-failed class java.lang.Class<org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper>: java.lang.NoClassDefFoundError: Failed resolution of: Lnet/sqlcipher/database/SQLiteOpenHelper;
        at void co.chatsdk.core.dao.DaoCore.openDB() (DaoCore.java:81)
        at void co.chatsdk.core.dao.DaoCore.init(android.content.Context) (DaoCore.java:65)
        at co.chatsdk.core.session.ChatSDK co.chatsdk.core.session.ChatSDK.initialize(co.chatsdk.core.session.Configuration) (ChatSDK.java:34)
```

**Comment by eakteam** [comment] 2018-06-13 00:44
# If you do not use SQLCipher:
-dontwarn org.greenrobot.greendao.database.**

so you should inform proguard to keep thoose classes

**Comment by agustinsivoplas** [comment] 2018-06-13 19:13
I am in develop mode

**Comment by thecmart** [comment] 2019-06-28 14:43
@agustinsivoplas We could not reproduce this problem in the newest version of Chat SDK, so we will close this issue. If the issue persists, please re-open it.

**Closed by thecmart** 2019-06-28 14:43 UTC
Labels: Cannot reproduce in version 4.4.9
