### ISSUE TITLE
Images are sideways

### ISSUE THREAD

**Issue by RogerRabbit91** [chat-sdk/chat-sdk-android#205] opened 2017-12-22 14:57 UTC
All images come in sideways and low resolution. Is there a way to fix this?

**Comment by thecmart** [comment] 2019-06-28 13:48
@RogerRabbit91 We could not reproduce this problem in the newest version of Chat SDK, so we will close this issue. If the issue persists, please re-open it.

**Closed by thecmart** 2019-06-28 13:48 UTC
Labels: Cannot reproduce in version 4.4.9
