### ISSUE TITLE
Take photo permission bug

### ISSUE THREAD

**Issue by agustinsivoplas** [chat-sdk/chat-sdk-android#286] opened 2018-05-30 14:39 UTC
I am able to pick a photo from gallery but I am not able to take a picture from camera. 
Version 4.0.26 running Android P  on Google Pixel. Also If I add the permission from Settings/Apps the app crash when I take the picture.

<img width="476" alt="screen shot 2018-05-30 at 11 36 32" src="https://user-images.githubusercontent.com/1648539/40727319-04f105fe-63fe-11e8-9576-82a64e7bc2f4.png">

**Comment by milkiway** [comment] 2018-08-13 08:26
Issue seems to be fixed in 4.1.8

**Comment by thecmart** [comment] 2019-06-28 14:44
@agustinsivoplas We could not reproduce this problem in the newest version of Chat SDK, so we will close this issue. If the issue persists, please re-open it.

**Closed by thecmart** 2019-06-28 14:44 UTC
Labels: Cannot reproduce in version 4.4.9
