### ISSUE TITLE
Chat message not received occasionally, after idling for a while

### ISSUE THREAD

**Issue by brucexia** [chat-sdk/chat-sdk-android#164] opened 2017-10-31 16:51 UTC
I noticed my message was not getting delivered/received this morning after leaving the sample apps idle for maybe half hour or so. Is this known issue? Could this be firebase issue? Not seeing it yet after restarting the app.

**Comment by bensmiley** [comment] 2017-10-31 18:13
Can you check to see if they are being added correctly to Firebase? This sounds like `goOffline` is being called and then `goOnline` isn't being called again. When you look at the Firebase data is the user shown as online i.e. user/online = true? It would be worth adding some logging into these two methods.

**Comment by brucexia** [comment] 2017-10-31 18:48
@bensmiley so for user a and b, user a can receive message from b, but user b is not receiving from a. In the database, only user a is online. So it looks like the the currentUserOn is not being triggered after the app comes back

**Comment by brucexia** [comment] 2017-10-31 21:59
The AppBackgroundMonitor.enabled = false

**Comment by Allansk2** [comment] 2017-11-01 03:26
I have the same issue, it's with the old version, #140, but I tested again with the new version, from the firebase api, firebase auto disconnect after 60 seconds of iding, but the goOnline method sometimes doesn't get the user connected back to firebase.

**Comment by brucexia** [comment] 2017-11-01 05:30
@Allansk2 that's different. In my case the problem isnt with firebase connection - it's still connected but somehow all event listeners are removed and the user online status is not set.

**Comment by brucexia** [comment] 2017-11-01 15:33
@bensmiley any suggestion how this could be fixed? I think AppBackgroundMonitor is the problem but I don't see obviously where it could go wrong.

**Comment by bensmiley** [comment] 2017-11-02 09:27
From what you've said, it looks like `logout` has been called. Calling log out will generally disable the background monitor and remove the firebase references. It should also start the Login activity. 

The purpose of the background monitor is to set the user offline if the app is closed for more than a set period of time. It won't remove any listeners. 

I've not seen this issue so far in testing and I can't seem to replicate it. Have you made any changes to the project? Can you replicate this with the default unmodified version from Github?

Could you checkout the default version of the product and try to find a sequence of steps that I can use to reproduce the issue?

**Comment by Yariko-chan** [comment] 2017-11-02 13:48
I'm facing similar issue now - randomly chat stop receive messages from server, however, messages I send from the same chat appear in firebase. If I restart chat, I'll continue not receive messages from server. The user stays online during being in chat, as I can see in firebase, and also authenticated.

Let me explain how we use ChatSDK - may be this will clear up the situation. 
The library was integrated inside app which already has a firebase. We used only core, firebase_adapter and ui modules. ChatSDK configured in Application onCreate(). When user login in app, it also login in chat with the same data. Later user can create private 1to1 chat with other user (using NM.thread().createThread(List<User>) and pass threadId to that user. User opens Chat (InterfaceManager.shared().a.startChatActivityForID() ) and starts chatting. 
Any chance I missed something and therefore this problem occurs?

**Comment by OferRnz** [comment] 2017-11-02 18:11
The following may (or may not) be related:
Issue #154, which is now closed, exhibited the same exact behavior after the crash (see my comment there).
(@rohitbhoite : There was no fetching pop up showing).
This is easily reproducible and may provide a hint as to what leads to this type of behavior.
And yet again, it may be totally unrelated :)
I hope this helps.

**Comment by brucexia** [comment] 2017-11-02 18:31
@bensmiley No I reproduced it several times without logout. The only change I made to the sample app is the firebase credentials so I can see the data.

**Comment by Yariko-chan** [comment] 2017-11-10 13:50
In my case one of the problem was that I keep my users authorised until they explicitly click "Logout", so after app restart `disposableList `in `FirebaseEventHandler `is void and subscribing to `source()` and `sourceOnMain()` doesnt work. To solve the problem, I call `FirebaseEventHandler.shared().currentUserOn(); `after restart. Hope this help someone.

But also may be some other problem exist, because while debugging I noticed that disposableList contains disposables, that already disposed - this shouldn't be because disposableList.dispose clears list, so they disposed by some other reason, not by logging out or something else. I can;t reproduce it know.

**Comment by bensmiley** [comment] 2017-11-10 15:28
When the app starts up, you should at least call `NM.auth().authenticateWithCachedToken()` this will do the necessary setup. 

With regards to the disconnect issue, I'm adding a fix to the latest version. Hopefully it will help.

**Comment by Yariko-chan** [comment] 2017-11-10 16:11
@bensmiley thanks a lot! I forgot about this option)

**Comment by bensmiley** [comment] 2017-11-13 19:32
This issue should be fixed in the latest release. Please re-open the issue if it still persists.

**Closed by bensmiley** 2017-11-13 19:32 UTC
Labels: investigating

**Comment by Mahmoud-S-Ali** [comment] 2020-06-14 10:55
I haven't tried the latest version yet '5.0.0rc7', but I fixed the issue by calling:
`if (ChatSDK.auth().isAuthenticated()) {
            disposableList.add(ChatSDK.auth().authenticate()
                    .subscribe(new Action() {
                        @Override
                        public void run() throws Exception {
                            afterAuthentication();
                        }
                    }, throwable -> logError(throwable.getMessage())));
        }`

at the start of my activity
