### ISSUE TITLE
How to create new chat thread from existing application

### ISSUE THREAD

**Issue by myeduapp** [chat-sdk/chat-sdk-android#155] opened 2017-10-26 11:29 UTC
I have integrated the chat sdk in existing android project and its working fine.
I would like to implement below functionality 
1. create new chat thread from existing application
2. Set username when the plugin is initialized.(I would like to set username which is chosen by user in the existing application and wants to use same in the chat plugin also).
How this  can be achieved in a proper way?

**Comment by bensmiley** [comment] 2017-10-26 15:05
I would recommend looking at this [guide](https://github.com/chat-sdk/docs). It's not complete but it should provide some help. 

For the username, the best approach would be to use custom authentication. See [part 1](https://github.com/chat-sdk/chat-sdk-ios#login) and [part 2](https://github.com/chat-sdk/docs#custom-authentication). This way, Firebase would always be authenticated by **your** server. So if the user changed their password, this wouldn't affect Firebase.

**Comment by myeduapp** [comment] 2017-10-27 08:10
@bensmiley Thanks for sharing the above link.I will read it.I am not able to search the contacts.It is showing
" Fetching...." popup forever.

**Comment by bensmiley** [comment] 2017-10-31 10:04
This issue was caused by the way we were retrieving the contacts from Firebase. I've updated the code to make the search request a **single value** event rather than an **on child added listener**. This will be fixed in the next commit.

**Comment by OmarAlbelbaisy** [comment] 2017-11-26 03:46
It's seems the search problem still exist in the latest version @bensmiley

**Comment by bensmiley** [comment] 2017-12-14 17:33
Fixed in `4.0.7`.

**Closed by bensmiley** 2017-12-14 17:33 UTC
Labels: investigating
