### ISSUE TITLE
Phone Authentication issue

### ISSUE THREAD

**Issue by dlaravindhan** [chat-sdk/chat-sdk-android#223] opened 2018-01-06 14:26 UTC
I have problem when i am first time install the application that is just show progress bar loading.....

i am just add your code in co.chatsdk.firebase.ui         FirebaseUIActivity         

 FirebaseUIModule.activate(context, AuthUI.PHONE_VERIFICATION_PROVIDER); 

in onCreate method.

but second time run the app that works fine. What can i do rectify this problem

**Comment by thecmart** [comment] 2019-06-28 14:02
@dlaravindhan We could not reproduce this problem in the newest version of Chat SDK, so we will close this issue. If the issue persists, please re-open it.

**Closed by thecmart** 2019-06-28 14:02 UTC
Labels: Cannot reproduce in version 4.4.9, investigating
