### ISSUE TITLE
Not receiving push notifications.

### ISSUE THREAD

**Issue by dreimanis** [chat-sdk/chat-sdk-android#189] opened 2017-11-23 14:25 UTC
I'm using this whole project (4.0.0). Changed all the strings to my firebase. Chat is working fine, but I'm not receiving push notifications.
What I understood I just need to change `firebase_cloud_messaging_server_key` in `chat-sdk-android-master\app\src\main\res\values\string.xml` to my key.

Everything else stays the same ?

**Comment by dreimanis** [comment] 2017-11-24 11:48
I installed your app with your server settings, made 2 accounts on 2 different phones. Added my self. And first time I wrote to my other account, it sent notification. But that's it, it worked once.

**Comment by bensmiley** [comment] 2017-11-24 13:26
Have you enabled the [push notifications module](https://github.com/chat-sdk/chat-sdk-android#push-notifications) and done the necessary setup?

**Comment by dreimanis** [comment] 2017-11-24 13:39
Yes, like I said. I just downloaded this whole project , changed links to my firebase server, switched the json file. Chat is working. Just the notifications aren't working. 
It working strange, sometimes when I delete app, reinstall it and log in , it sends me notification ( only once ). So I'm guessing all the firebase stuff is correct, it worked once or twice , but not anymore.

**Comment by bensmiley** [comment] 2017-11-24 13:40
Can you send me the setup code you are using? i.e. the code you are putting in your `app.onCreate` method.

**Comment by dreimanis** [comment] 2017-11-24 13:43
I didn't change anything, its the same as here. 
https://github.com/chat-sdk/chat-sdk-android/blob/master/app/src/main/java/co/chatsdk/android/app/AppObj.java

**Comment by bensmiley** [comment] 2017-11-24 13:46
Can you do the following - get the app running on two devices (A and B). Then kill the app on A and send then send a message from B to A. Tell me if a push comes through.

**Comment by dreimanis** [comment] 2017-11-24 13:50
Nothing happened.

**Comment by bensmiley** [comment] 2017-11-24 16:32
I'll need to do some testing to see if I can reproduce the issue.

**Comment by dreimanis** [comment] 2017-11-28 07:16
Also. With iOS app, it created "pushToken" field for every user I login in firebase Database.
Does not create when I login from Android.

**Comment by bensmiley** [comment] 2017-11-28 20:41
This seems to be a bug with the Android push code. I'm hoping to have a fix ready tomorrow.

**Comment by bensmiley** [comment] 2017-12-01 10:59
This should be fixed in the latest version - [4.0.6](https://github.com/chat-sdk/chat-sdk-android/releases/tag/4.0.6).

**Comment by dreimanis** [comment] 2017-12-04 12:14
I updated, but now I get `FirebasePushHandler: Push response: Response{protocol=h2, code=401, message=, url=https://fcm.googleapis.com/fcm/send}` 
Everything works, but no notifications. Did I mess up somewhere in google-services.json ?

**Closed** 2017-12-05 07:30 UTC
Labels: bug
